### ISSUE TITLE
Does not work correctly with the latest patch

### ISSUE THREAD

**Issue by pixelbart** [Ellypse/Storyline#56]
Since the last patch (preparation for shadow landing) the texts are no longer shown in the text window, but leave the window and are displayed next to the window. Otherwise I haven't found any bugs yet.

**Comment by uujfwmnp** [comment]
There are two errors that I can see:
```
1x Storyline\lib\Ellyb\Tools\Colors-Colors.lua:44: attempt to compare number with nil
[string "@Storyline\lib\Ellyb\Tools\Colors-Colors.lua"]:44: in function `initialize'
[string "@Storyline\lib\Ellyb\Libraries\middleclass.lua"]:154: in function `new'
[string "@Storyline\lib\Ellyb\Tools\ColorsManager.lua"]:156: in main chunk

Locals:
self = <table> {
 class = <table> {
 }
}
red = nil
green = nil
blue = nil
alpha = nil
(*temporary) = "nil"
(*temporary) = nil
(*temporary) = "nil"
(*temporary) = <table> {
 canBeMutated = true
}
(*temporary) = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
(*temporary) = "attempt to compare number with nil"
_privateInit = <function> defined @Storyline\lib\Ellyb\Tools\Colors.lua:19
Ellyb = <table> {
}
```

```
1x ...line\lib\CustomTutorials-2.1\CustomTutorials-2.1-8.lua:149: attempt to call method 'SetBackdrop' (a nil value)
[string "@Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1-8.lua"]:149: in function <...line\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua:124>
[string "@Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1-8.lua"]:181: in function `RegisterTutorials'
[string "@Storyline\Tutorials.lua"]:28: in function `register'
[string "@Storyline\events.lua"]:842: in function `initEventsStructure'
[string "@Storyline\logic.lua"]:637: in function <Storyline\logic.lua:467>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
```

The second error is a simple fix inside `\Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua` -- just have to change lines 148 and 149 to this:
```
    local shine = CreateFrame("Frame", nil, UIParent, BackdropTemplateMixin and "BackdropTemplate");
    shine:SetBackdrop({edgeFile = 'Interface\\TutorialFrame\\UI-TutorialFrame-CalloutGlow', edgeSize = 16});
```
Still not sure how to fix the other one.

**Comment by uujfwmnp** [comment]
Another error popped up:
```
1x Storyline\events.lua:786: attempt to call field 'text' (a nil value)
[string "@Storyline\events.lua"]:786: in function <Storyline\events.lua:784>

Locals:
(*temporary) = <function> defined @Storyline\logic.lua:196
(*temporary) = "npc"
(*temporary) = nil
(*temporary) = "attempt to call field 'text' (a nil value)"
storylineFrameShouldOpen = true
startDialog = <function> defined @Storyline\logic.lua:196
info = <table> {
 finishMethod = <function> defined @Storyline\events.lua:716
 finishText = <function> defined @Storyline\events.lua:727
}
event = "GOSSIP_SHOW"
```

**Comment by Ellypse** [comment]
Thanks for the report. I will try to get to fix Storyline when I get some time, but due to personal maters this could take a few days. I had some basic work done during beta that could already help.

**Comment by Ellypse** [comment]
I just published a [3.2.0 beta build](https://www.curseforge.com/wow/addons/storyline/files/3082317) with basic fixes that should cover the Lua errors reported here. I didn't have time to do extensive testing for all the weird quests out there, so if you come across unhandled edge cases please do not hesitate to report them here :)

**Comment by Stravides** [comment]
I also receive these errors. After applying 3.2.0 beta build I also still get the following errors.  This is on load - not when clicking anything.

```
Message: ...nterface\AddOns\Storyline\lib\Ellyb\Tools\Colors.lua:44: attempt to compare number with nil
Time: Fri Oct 16 09:19:26 2020
Count: 1
Stack: ...nterface\AddOns\Storyline\lib\Ellyb\Tools\Colors.lua:44: attempt to compare number with nil
[string "@Interface\AddOns\Storyline\lib\Ellyb\Tools\Colors.lua"]:44: in function `initialize'
[string "@Interface\AddOns\Storyline\lib\Ellyb\Libraries\middleclass.lua"]:154: in function `new'
[string "@Interface\AddOns\Storyline\lib\Ellyb\Tools\ColorsManager.lua"]:156: in main chunk

Locals: self = <table> {
 class = <table> {
 }
}
red = nil
green = nil
blue = nil
alpha = nil
(*temporary) = "nil"
(*temporary) = nil
(*temporary) = "nil"
(*temporary) = <table> {
 canBeMutated = true
}
(*temporary) = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
(*temporary) = "attempt to compare number with nil"
_privateInit = <function> defined @Interface\AddOns\Storyline\lib\Ellyb\Tools\Colors.lua:19
Ellyb = <table> {
}

```
And 
```
Message: ...line\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua:149: attempt to call method 'SetBackdrop' (a nil value)
Time: Fri Oct 16 09:19:35 2020
Count: 1
Stack: ...line\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua:149: attempt to call method 'SetBackdrop' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua"]:149: in function <...line\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua:124>
[string "@Interface\AddOns\Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua"]:181: in function `RegisterTutorials'
[string "@Interface\AddOns\Storyline\Tutorials.lua"]:28: in function `register'
[string "@Interface\AddOns\Storyline\events.lua"]:842: in function `initEventsStructure'
[string "@Interface\AddOns\Storyline\logic.lua"]:637: in function <Interface\AddOns\Storyline\logic.lua:467>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:689: in function `OrderHall_LoadUI'
[string "@Interface\AddOns\Immersive\Modules\Default\Frames\OrderHallCommandBar.lua"]:14: in function `RegisterOrderHallCommandBar'
[string "@Interface\AddOns\Immersive\Modules\Default\Module.lua"]:65: in function `OnEnable'
[string "@Interface\AddOns\Immersive\Framework\Engine.lua"]:91: in function `Enable'
[string "@Interface\AddOns\Immersive\Framework\Engine.lua"]:27: in function <Interface\AddOns\Immersive\Framework\Engine.lua:22>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
```

When I click on quest person  I get another error 

```
Message: Interface\AddOns\Storyline\events.lua:790: attempt to call field 'text' (a nil value)
Time: Fri Oct 16 09:22:53 2020
Count: 1
Stack: Interface\AddOns\Storyline\events.lua:790: attempt to call field 'text' (a nil value)
[string "=[C]"]: in function `text'
[string "@Interface\AddOns\Storyline\events.lua"]:790: in function `callback'
[string "@Interface\AddOns\Storyline\lib\Ellyb\Tools\EventsDispatcher.lua"]:74: in function `TriggerEvent'
[string "@Interface\AddOns\Storyline\lib\Ellyb\Tools\GameEvents.lua"]:43: in function <...face\AddOns\Storyline\lib\Ellyb\Tools\GameEvents.lua:41>

Locals: 
```

**Comment by fitsou** [comment]
is the addon dead? its been awhile since it got an update

**Comment by Ellypse** [comment]
@fitsou The add-on is not dead. There's a [beta build for version 3.2.0](https://www.curseforge.com/wow/addons/storyline/files/3084604) with fixes for patch 9.0.1. Once the beta has been tested enough I will push a release (which should happen today or tomorrow depending on when I have the time to do it).

**Comment by fitsou** [comment]
@Ellypse so glad to hear that! Thanks for the update.
It’s the best add on of its kind!!

**Comment by Ellypse** [comment]
Version 3.2.0 is now available with the fixes.
